import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function MenuLayout(
    { children, }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
            <body>
                <header style={{
                    backgroundColor: "lightblue",
                    padding: "1rem"
                }}>
                    <p>Todo Header</p>
                </header>
                {children}
                <footer style={{
                    backgroundColor: "lightgreen",
                    padding: "1rem"
                }}>
                    <p>Todo Footer</p>
                </footer>
            </body>
        </html>
    );
}
